import { Types } from "mongoose";
export interface IUserModel {
  _id: Types.ObjectId;
  email: string;
  password: string;
  phone: string;
  fullname: string;
  isVerified: boolean;
  createdAt: Date;
  updatedAt: Date;
  isBlocked:boolean;
  isDeleted:boolean;
  onboardingCompleted: boolean;
  height?: number;
  heightUnit?: "cm" | "ft/in";
  weight?: number;
  weightUnit?: "kg" | "lbs";
  age?: number;
  gender?: "Male" | "Female" | "Other" | "Prefer not to say";
  activityLevel?: "Sedentary" | "Lightly Active" | "Moderately Active" | "Very Active" | "Extremely Active";
  bmi?: number;
  bmiCategory?: "Underweight" | "Normal Weight" | "Overweight" | "Obese";
  healthGoal?: string;
  dietaryPreference?: string;
  allergies?: string[];
  foodPreferences?: string[];
  preferredCuisines?: string[];
  mealsPerDay?: number;
  dailyCalorieTarget?: number;
}